name: CI - Dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "dist/**"

  pull_request:
    branches:
      - dev

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v5
        with:
          ref: dev
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar build
        run: npm run build

      - name: Comitar pasta dist na branch dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f dist

          if git diff --cached --quiet; then
            echo "Nenhuma alteração na pasta dist."
          else
            git commit -m "build: atualizar pasta dist [skip ci]"
            git push origin dev
          fi